export const PATHS = {
    HOME: '/',
    ACCOUNT: '/account',
    ORDERS: '/account/order-history',
    PROFILE_SETTINGS: '/account/edit-profile',
    PASSWORD_SETTINGS: '/account/edit-password',
    CART: '/cart',
    CHECKOUT: '/checkout',
    COLLECTION: '/collections/:collection',
    CONTACT: '/contact',
    FAQ: '/faq',
    LOGIN: '/login',
    SHOP: '/shop',
    PRODUCT: '/shop/:id',
    SIGNUP: '/signup',
};
